dbt_fabric_test:
  target: dev
  outputs:
    dev:
      type: fabric
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: e5zvzpbowhnurkcwc5kzd3gs6a-ukt4bcw2wcxuhl7dgytpiav7ge.datawarehouse.fabric.microsoft.com
      port: 1433
      database: WH_test
      schema: dbo
      authentication: ServicePrincipal
      tenant_id: bc5c7327-b12e-48db-a856-175591ecd2f0
      client_id: 9acf00a5-b63c-4689-99ad-33eab21eabac
      client_secret: C338Q~Nys15WtW4jolfkB7mMIr7OE.70zLWRLaVb